### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cferdinandi** [easydigitaldownloads/EDD-Download-All#1]
Hey there! No issue or anything. Just wanted to give you a massive THANK YOU for this.

I sell ebooks, and because people want to be able to just click a link and start reading on their mobile devices (particularly iOS), I upload individual files instead of a packaged zip. *But*, a lot of folks also ask for a "download all" option.

This plugin is insanely useful. One WP plugin author to another: I appreciate the time you put into developing it. Cheers!

**Comment by pippinsplugins** [comment]
Glad to hear it!
